name: Update AoC Badges
on:
  push:
    branches:
      - "main"

  workflow_dispatch: # allow to manually start the workflow

# push:                                          # (disabled) run on push, be carefull with this setting
# as the workflow should only be triggered at a rate lower than
# 4 times a hour to keep traffic on aoc site low
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # clones your repo

      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 2509671 # your user id, see setup on how to obtain
          session: ${{ secrets.AOC_SESSION }} # secret containing session code, see setup on how to obtain

      - uses: stefanzweifel/git-auto-commit-action@v4 # Step that pushes these local changes back to your github repo
        with:
          commit_message: Update badges
          file_pattern: README.md
